# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/3180105910_lab30/vivado201704/Risc5CPU.srcs/sources_1/ip/DataMemory/DataMemory.xci
# IP: The module: 'DataMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/3180105910_lab30/vivado201704/Risc5CPU.srcs/sources_1/ip/DataMemory/DataMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataMemory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/3180105910_lab30/vivado201704/Risc5CPU.srcs/sources_1/ip/DataMemory/DataMemory.xci
# IP: The module: 'DataMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/3180105910_lab30/vivado201704/Risc5CPU.srcs/sources_1/ip/DataMemory/DataMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataMemory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
